const students = [
  {
    id: 1,
    name: 'Big Boss Man Adolf, AKA Abduladolf (Mr. Funny)',
    country: 'n/a',
    likes: 'n/a',
    dislikes: 'n/a',
    interesting_fact: '',
    img: 'https://www.pngitem.com/pimgs/m/258-2584491_kenny-south-park-png-transparent-png.png',
    bio: 'Homework loves you.',
    button_id: 'abduladolf',
    status: 'active',
  },
  {
    id: 2,
    name: 'President Amin',
    country: 'Saudi Arabia',
    likes: 'Eggs and cheese',
    dislikes: 'Not eating eggs and cheese',
    interesting_fact: '',
    img: 'https://i1.sndcdn.com/artworks-000379239159-qi6n15-t500x500.jpg',
    bio: 'Likes bread, cheese, eggs (sometimes chicken) for breakfast.',
    button_id: 'amin',
    status: 'active',
  },
  {
    id: 3,
    name: 'Rashed',
    likes: 'n/a',
    dislikes: 'n/a',
    interesting_fact: '',
    country: 'Saudi Arabia',
    img: 'https://preview.redd.it/erimg7yicns41.jpg?auto=webp&s=6f1d86315cef37dc5f8d71edb613271614b28604',
    bio: 'First graduate to move up to the next level.',
    button_id: '',
    status: 'graduate',
  },
  {
    id: 4,
    name: 'Abdulaziz',
    likes: 'After parties',
    dislikes: 'No after parties',
    interesting_fact: '',
    country: 'Saudi Arabia',
    img: 'https://i1.sndcdn.com/avatars-000022201824-zd09tb-t500x500.jpg',
    bio: "Sometimes Papa Mutaz. Sometimes sneaks in to clean Mutaz's room.",
    button_id: 'aziz',
    status: 'active',
  },
  {
    id: 5,
    name: 'Nasser',
    likes: 'Recording video selfies, Club Nasser',
    dislikes: 'Homework',
    interesting_fact: '',
    country: 'Saudi Arabia',
    img: 'https://us.123rf.com/450wm/mickallnice/mickallnice1705/mickallnice170500002/77255576-kid-doing-a-homework-vector-and-illustration.jpg?ver=6',
    bio: 'Loves doing homework every day, but also has homework phobia.',
    button_id: 'nasser',
    status: 'active',
  },
  {
    id: 6,
    name: 'Jenny',
    likes: 'The beach',
    dislikes: 'n/a',
    interesting_fact: '',
    country: 'Taiwan',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNCNwfy7UW0lHwx6p8BPlTNgclkr3pMCIDBHfQGJJKDsOvEOX4GxhrX5lpWgwqayOF7VA&usqp=CAU',
    bio: 'Wants to go on vacation. Loves taking pictures of the sunset.',
    button_id: 'jenny',
    status: 'active',
  },
  {
    id: 7,
    name: 'Mohammad',
    likes: 'Donuts',
    dislikes: 'A class without donuts',
    interesting_fact: '',
    country: 'Saudi Arabia',
    img: 'https://ih1.redbubble.net/image.986147108.2204/pp,840x830-pad,1000x1000,f8f8f8.jpg',
    bio: 'Bringer of donuts.',
    button_id: '',
    status: 'active',
  },
  {
    id: 8,
    name: 'Saleh',
    likes: 'n/a',
    dislikes: 'n/a',
    interesting_fact: '',
    country: 'Saudi Arabia',
    img: 'https://i.pinimg.com/originals/dd/0a/7b/dd0a7b1b9cbf38774f80e4b9042608ea.jpg',
    bio: 'Fresh new haircut and Kahoot winner.',
    button_id: '',
    status: 'active',
  },
  {
    id: 9,
    name: 'Mutaz',
    likes: 'Hanging out with friends',
    dislikes: 'Nosy people',
    interesting_fact: '',
    country: 'Saudi Arabia',
    img: 'https://entertainment.time.com/wp-content/uploads/sites/3/2013/05/fictioninfluence_list_homersimpson.jpg',
    bio: 'In charge of break time. Cleans his ears every day.',
    button_id: 'mutaz',
    status: 'graduate',
  },
  {
    id: 10,
    name: 'Masaumi',
    likes: 'Sleep, baseball, and dogs',
    dislikes: 'Not sleeping',
    interesting_fact: '',
    country: 'Japan',
    img: 'https://static.vecteezy.com/system/resources/previews/006/922/012/original/cute-boy-with-pug-dog-and-corgi-dog-cartoon-icon-illustration-animal-people-icon-concept-isolated-premium-vector.jpg',
    bio: 'Has two cute chihuahuas and loves baseball.',
    button_id: '',
    status: 'graduate',
  },
  {
    id: 11,
    name: 'Michelle',
    likes: 'San Diego',
    dislikes: 'Working as an accountant',
    interesting_fact: '',
    country: 'Taiwan',
    img: 'https://us.123rf.com/450wm/esheluxina/esheluxina1811/esheluxina181100153/127708976-business-and-finance-flat-style-vector-illustration-clipart-.jpg?ver=6',
    bio: 'Comes from Taiwan and works as an accountant.',
    button_id: 'michelle',
    status: 'active',
  },
  {
    id: 12,
    name: 'Yazeed',
    likes: 'Pasta and waka waka',
    dislikes: 'Bananas and cold weather',
    interesting_fact: '',
    country: 'Saudi Arabia',
    img: 'https://clickclack.es/WebRoot/Store14/Shops/536773c5-8a25-42ea-8b30-6260eeefd1b5/629B/05BA/0602/3EEA/652D/0A48/3559/1587/_KAI9022_ml.JPG',
    bio: 'My name is Yazeed. Waka waka waka.',
    button_id: 'yazeed',
    status: 'active',
  },
  {
    id: 13,
    name: 'Bader',
    likes: 'Arabic music and Johnny Cash',
    dislikes: 'Homework',
    interesting_fact: '',
    country: 'Saudi Arabia',
    img: 'https://th.bing.com/th/id/R.ff061c5054e6a32b783555964a2f3e54?rik=zSvwCku7bIGOhw&riu=http%3a%2f%2fpre03.deviantart.net%2fff82%2fth%2fpre%2fi%2f2013%2f059%2fe%2f1%2fmoustache_iron_man_by_future_parker-d5whjo5.png&ehk=go%2brbgkl2ZSQGWklblsClGiL%2ferEhzZAj1DPUR27hNk%3d&risl=&pid=ImgRaw&r=0',
    bio: 'Do you like my moustache?',
    button_id: 'bader',
    status: 'active',
  },
  {
    id: 14,
    name: 'Viviana',
    likes: 'n/a',
    dislikes: 'n/a',
    interesting_fact: 'n/a',
    country: 'Colombia',
    img: 'https://thumbs.dreamstime.com/b/colombian-woman-coffee-collector-vector-illustration-design-88068746.jpg',
    bio: 'Nice to meet you!',
    button_id: '',
    status: 'active',
  },
  {
    id: 15,
    name: 'Joao',
    likes: 'Soccer and Carnival',
    dislikes: 'Homework',
    interesting_fact: '',
    country: 'Brazil',
    img: 'https://media.istockphoto.com/vectors/brazil-sport-fan-with-flag-and-horn-vector-id486835873?k=20&m=486835873&s=612x612&w=0&h=3cN_3NL6sDw3dMJkg9BSu6Jed1ATbh2rA_QhQ0TbzXQ=',
    bio: 'I love Brazil!',
    button_id: 'joao',
    status: 'active',
  },
];

export default students;
